#include<iostream>
using namespace std;
int main(){
    int i,j,n;
    char ch;
    cout<<"Enter the value of n"<<endl;
    cin>>n;
    for(int i=0;i<=n;i++){
        for(int j=0;j<=i;j++){
            ch='A'+i;
            
            cout<<ch<<" ";
            ch++;
            
            
            

            
            
           
            
        }
        
        cout<<endl;
    }
   
    
}